# Generated by Django 4.2.7 on 2025-11-04 03:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата резервного копирования"
                    ),
                ),
                (
                    "backup_file",
                    models.CharField(
                        max_length=500, verbose_name="Файл резервной копии"
                    ),
                ),
                ("backup_size", models.BigIntegerField(verbose_name="Размер (байты)")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Ошибка")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
            ],
            options={
                "verbose_name": "Журнал резервного копирования",
                "verbose_name_plural": "Журналы резервного копирования",
                "ordering": ["-backup_date"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер бронирования"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала тура")),
                ("end_date", models.DateField(verbose_name="Дата окончания тура")),
                (
                    "number_of_participants",
                    models.PositiveIntegerField(verbose_name="Количество участников"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Общая стоимость (₸)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("paid", "Оплачено"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Наличные"),
                            ("card", "Банковская карта"),
                            ("kaspi", "Kaspi Pay"),
                            ("halyk", "Halyk Bank"),
                            ("transfer", "Банковский перевод"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Особые пожелания"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите корректный номер телефона Казахстана (например: +77001234567)",
                                regex="^\\+?7?\\d{10}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "iin",
                    models.CharField(
                        help_text="Индивидуальный идентификационный номер",
                        max_length=12,
                        unique=True,
                        verbose_name="ИИН",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(max_length=20, verbose_name="Номер паспорта"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                ("address", models.TextField(verbose_name="Адрес")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название маршрута"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "start_location",
                    models.CharField(max_length=200, verbose_name="Начальная точка"),
                ),
                (
                    "end_location",
                    models.CharField(max_length=200, verbose_name="Конечная точка"),
                ),
                (
                    "intermediate_points",
                    models.TextField(
                        help_text="Укажите через точку с запятой",
                        verbose_name="Промежуточные точки",
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Общая дистанция (км)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.DurationField(verbose_name="Примерная продолжительность"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Легкий"),
                            ("medium", "Средний"),
                            ("hard", "Сложный"),
                            ("extreme", "Экстремальный"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Уровень сложности",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршруты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название тура"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "tour_type",
                    models.CharField(
                        choices=[
                            ("nature", "Природные достопримечательности"),
                            ("cultural", "Культурный туризм"),
                            ("adventure", "Приключенческий туризм"),
                            ("ski", "Горнолыжный туризм"),
                            ("health", "Оздоровительный туризм"),
                            ("business", "Деловой туризм"),
                            ("eco", "Экотуризм"),
                        ],
                        default="nature",
                        max_length=50,
                        verbose_name="Тип тура",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена указывается в тенге",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Цена (₸)",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="Длительность (дней)"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        verbose_name="Макс. количество участников"
                    ),
                ),
                (
                    "min_participants",
                    models.PositiveIntegerField(
                        verbose_name="Мин. количество участников"
                    ),
                ),
                (
                    "included_services",
                    models.TextField(
                        help_text="Укажите через точку с запятой",
                        verbose_name="Включенные услуги",
                    ),
                ),
                (
                    "excluded_services",
                    models.TextField(
                        blank=True,
                        help_text="Укажите через точку с запятой",
                        verbose_name="Не включенные услуги",
                    ),
                ),
                (
                    "accommodation_type",
                    models.CharField(max_length=100, verbose_name="Тип размещения"),
                ),
                (
                    "meals_included",
                    models.CharField(
                        choices=[
                            ("none", "Без питания"),
                            ("breakfast", "Завтрак"),
                            ("half_board", "Полупансион"),
                            ("full_board", "Полный пансион"),
                            ("all_inclusive", "Все включено"),
                        ],
                        default="breakfast",
                        max_length=50,
                        verbose_name="Питание",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для бронирования"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("year_round", "Круглогодично"),
                            ("summer", "Летний сезон"),
                            ("winter", "Зимний сезон"),
                            ("spring", "Весенний сезон"),
                            ("autumn", "Осенний сезон"),
                        ],
                        default="year_round",
                        max_length=20,
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tours/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours",
                        to="booking.route",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тур",
                "verbose_name_plural": "Туры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="booking.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="booking.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="booking.tour",
                        verbose_name="Тур",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.tour",
                verbose_name="Тур",
            ),
        ),
    ]
